# Generated by Django 6.0 on 2025-12-31 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
